name: Mend Scan

on:
  push:
    branches:
      - vul_mixcase_fix
  pull_request:
    branches:
      - vul_mixcase_fix

jobs:
  scan:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Mend CLI
        run: |
          sudo curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend
          sudo chmod +x /usr/local/bin/mend

      - name: Run Mend Scan
        run: mend-cli scan --format json --output mend-report.json

      - name: Upload Mend Report
        uses: actions/upload-artifact@v3
        with:
          name: mend-report
          path: mend-report.json
